sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- npm run v
script:
- ng build --prod --aot
deploy:
  provider: s3
  access_key_id: AKIAJLVRWYTNCOOXE3MQ
  bucket: app.macbubi.com
  skip_cleanup: true
  local_dir: dist/plantio
  secret_access_key:
    secure: nBlAl282pj3SzR9QG52Kb4fx7h7Tz0MuJ2V+nAoZZ4wIbJ/C4+17G8hKeKaFX1brmiprwWFA5lw0ZIth02TRDFQUTEVy8YYw91wVbDTeiW/g1U6S0u/XnLR6xO+zGU2h5woYH0wP2Q9AkApMFjZ7epiQBw8hV3O3HvowFjIZk+I3a2USyDb+jhccVm9W30gySOSoueIwdartqxxVEhOsZlFQyRsrSOHYo3R8Q9YC9ZOiOShT4rzHrt1yA7ARHCBMOb7nilN6RFeZeUV/Y7wZ3Tk7y65fJi4JsUVJHtEDI5E/TQJeK2dD0VfdO6OWu97Pd5aMxDbX7PA1TsFvH4LGhIlwZl5P+ES8lIhTHEu0eo1Fv1P8YE2z+uYtXZ4g/LOT2d0aEtzwxL5G+GFhoVgwsnNXg4TgBWb7b16ScYjlwOeupSPGdZNsU1sFSlrDdK1l1RQn2AJv3ZpINLXbMCYQXZRDzXFEO3xV1newgXhlFrteP5F1db+3aYPlVYFDxzalM/PRLLkZxA7/XSw9hflxB6wPYzaE6wL561zXkzep1YO5BsVgs+UBWlIH8W7AbxdCzjLbekAG5woeIZZyKAai2LNQRoMHvMCq8rEpLgpVgdJQ5k/NJFvhXXCWHFeFybp1k9XQ7W1PMA1uWVN5FnwasHGevxEbsT3mUSbRhKMjg0w=
