sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm run v

script:
  - ng build --prod --aot
  
deploy:
  provider: heroku
  app:
    master: plant-io
  api_key:
    secure: Tb2gYGCLiwAuJPiIlyE9HpvMjt3qyYuE1wDcBMzhQAv+HH2MBWIy8cBGNRteWBetcCUxOzFPGwEk1ImEt/zE7TVvu7vEb2hc93LeysceSw2t44+WNDoZRiPX04vvbjE1BH3TwPOcnXZLHkvI+fZ1DtsNw0Xe7EiKnPhixFPrswTByVc5jetVXAMHIHKsBMnQUJFunXKqF7ouf0EGRN9U6qXB8aCoHgjnjdiO6lWYX4TIzRloj024EOnU8p+DSBHxbSE9hX8C4F6IuZh9mJuVq6SfcdSnFuGQlpxPcNxnyIj+jTR4VkFQfXflqhlHb7EES5VpPxp6oQCCBcXQJn5zg0W57KDHszD9CNtIFuUZvC1TTql50ehC/MJr/lEqkO+D+4li2U6NPlTDn0NBupQOMLdgc4A3pz6mFkJVkomWNm0SuC1ix43ltHfxg/7qPz1YiRlFj+XWPbQuwAzzppyTyHEikXPQl6FwIvJ1xNCM4EjrrSgYwJ0dxrWkJenLoJ3Ww/8wNnWr5ApVttyxNyaFYIWhWRsa8D7u8X7nFccq7TUh6/qkhnf8ciHR37ZcxcxyY3nkwAtdkSk4GM7ZcRksqDsS/H9RHA3jvlbOhNb+RerKnGeXlzM7Ir9t2somXqSPgoxKv76qxYzkK768+xBKRvIeNQLr4Jc04y7s7QDxfMk=
