sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- npm run v
script:
- ng build --prod --aot
deploy:
  provider: s3
  access_key_id: AKIAJKNF6E5IGB5VT7XA
  secret_access_key:
    secure: gk69YUbZSXKhKie68VIKSjzAsImg4ShbFSgmZ1opQX/rBOvGrUXyicGKsNgcSwKrYSWba2WsQWXgM+SaxDzinEGIaHYoQhF7BFv2c2ktTx1xIPhdUNYkGMz4QNt68hXYMyXwJS0sa1JLOi2nZz1UWZwr5opcK7T7ExSTlAcKN67qFe+DHXY3XIPbY/nu1d9BtitMSnTK3+D9K0xfpKMy6tSlXfqAc0uWL7Vw6AghdWBdEDFJyINqfq+74jC+ykrLsTQQhQES/uq1xjHrBiG2SPQnDX/1nnEpsmmee8/Jt4LaqTvj0Pq7FqI5I+fJ4dPDUaA7DdHVCT+ySUG7ccau4j9SsY1ByBwRrxIXZlUjy2n2jTL8prt8JOGmT5A/lhq9sVTxjppBiVOE1ULKmACN2uPG9ucOaOxNLHBf07ELgFVnjm//GHJ2F1oz9lJJ6a3LV3WuUvhsQ8C7MgDfJExrDx7whrPNKSCgJXpadYu1vHp6lZyyG2RzgSMnOHAc55AchDaDgGHzlihAR9vg5xB4rKm+lSAIxZTCQ+avoiZFBMB/jJfjVNDuAIMCZo+u8J2rsin07KmFreGBjDZIgOzR9CqZ76D85Mk7aBE8r5KD6Fyi0YbkYWuXWoVPKMPks622ghD/knvHT+v3fbmaOmi+hufxvy6w/4Rl/jk3D8eX3aM=
  bucket: app.macbubi.com
